Final group capstone - Book an Appointment
AbdelazizSoliman/Final-Capstone-Back-End pull request #32
Opened 2023-10-19 18:37 UTC by AbdelazizSoliman

**The following features were implemented in this project:**

- [ ] Set up Rails backend for the application
- [ ] Set up Api only rails
- [ ] Create Models
- [ ] Set up controllers for Doctors, Reservation, and Patients
- [ ] Add all API endpoints

2023-10-19 21:32 UTC, mcrd25 requested changes
Hi Team,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Documentation 👍 
- Basic functional requirements of application met 👍 
- Good attempt overall

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- You are missing tests, please add [IMPORTANT]
- Always consider what would happen is something does not work as should, check your controllers for consistent error handling [IMPORTANT]
- [OPTIONAL] removing the `test` directory since you are using `rspec` for testing and not native testing.
- [OPTIONAL] Consider using the `timecop` gem to freeze time when running tests. It can help avoid errors: https://github.com/travisjeffery/timecop
- 
[OPTIONAL] Should always have positive and negative tests to ensure it works the way you expect it. Eg. What do you expect the output to be when it's not valid or when valid etc.
Consider making all your tests more extensive, not just this one. For this simple application, it may not catch a possible crippling bug, but in bigger applications, it definitely can. Consider this for all projects moving forward.

# NOTE: Front-end review to follow soon, having slight technical difficulties, so you can start working on these

**Hope all is well, and that my comments were helpful. 😸**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
_Also, you do not have to implement all requested changes, as this is up to you in the end, but I strongly recommend you implement them._

2023-10-19 21:32 UTC, mcrd25 commented on README.md
> +Load the database schema with this command:
should hae instructions on migrations, inlcuding for Test env

2023-10-19 21:32 UTC, mcrd25 commented on spec/requests/api/v1/doctors_spec.rb
> +RSpec.describe 'Api::V1::Doctors', type: :request do
missing tests

2023-10-19 21:32 UTC, mcrd25 commented on spec/requests/api/v1/patients_spec.rb
> +RSpec.describe 'Api::V1::Patients', type: :request do
missing tests

2023-10-19 21:32 UTC, mcrd25 commented on spec/requests/api/v1/appointments_spec.rb
> +RSpec.describe 'Api::V1::Appointments', type: :request do
missing tests

2023-10-19 21:32 UTC, mcrd25 commented on spec/models/patient_spec.rb
> +RSpec.describe Patient, type: :model do
mssing tests

2023-10-19 21:32 UTC, mcrd25 commented on app/controllers/api/v1/appointments_controller.rb
> +    @results = ActiveRecord::Base.connection.execute(sql_query)
you shoudl avoid using raw swl in  your controllers

2023-10-19 21:32 UTC, mcrd25 commented on app/controllers/api/v1/appointments_controller.rb
> +      render json: { errors: @appointment.errors.full_messages, status: 'Failed' }, status: :unprocessable_entity
remove commented out code

2023-10-19 21:32 UTC, mcrd25 commented on app/controllers/api/v1/appointments_controller.rb
> +    @appointment = Appointments.find(params[:id])
since you have this code ina method already, why repeat

2023-10-19 21:32 UTC, mcrd25 commented on app/controllers/api/v1/appointments_controller.rb
> +    @appointment = Appointment.find(params[:id])
where is the error handling? what happens if it's not found?

2023-10-19 21:32 UTC, mcrd25 commented on app/controllers/api/v1/doctors_controller.rb
> +      .select('doctors.*', 'specializations.name AS specialization_name')
SEe my comments on sql in appointments controller

2023-10-19 21:32 UTC, mcrd25 commented on app/controllers/api/v1/doctors_controller.rb
> +      # render json: @doctor, status: :created
remove commented out code

2023-10-20 11:07 UTC, Meltrust approved these changes
#### Hi @AbdelazizSoliman,


# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)





Cheers and Happy coding!👏👏👏


------

2023-10-20 13:15 UTC, merged